show databases;
use students;
show tables;
select *from stdinfo;
insert into stdinfo(fname,lname,age)value("komal","mane",24);
start transaction;
insert into stdinfo(fname,lname,age)value("nikita","khapare",33);
commit;
rollback;
start transaction;
savepoint init;
update  stdinfo set fname = "piya" where id = 1;
savepoint upd;
delete from stdinfo where fname = "nikita";
savepoint del;
insert into stdinfo(fname,lname,age)value("siya","salunkhe",22);
savepoint ins;
rollback to upd;
truncate table stdinfo;
